[avito]
urls = ["https://www.avito.ru/..."]
count = 1
keys_word_white_list = []
keys_word_black_list = []
seller_black_list = []
max_price = 99999999
min_price = 0
geo = ""
proxy_string = ""
proxy_change_url = ""
pause_general = 1
pause_between_links = 1
max_age = 0
max_count_of_retry = 5
ignore_reserv = true
ignore_promotion = false
one_time_start = false
one_file_for_link = false
parse_views = false
save_xlsx = true
use_webdriver = false
use_bypass_api = false
cookies_api_key = ""
use_own_cookies = false
parse_phone = false
retry_delay = 5
timeout = 20
block_threshold = 3