name: "avito_dwh"
version: "1.0.0"
config-version: 2

profile: "avito_dwh"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  avito_dwh:
    core:
      +materialized: table
      +schema: core
    mart:
      +materialized: view
      +schema: mart