avito_dwh:
  outputs:
    dev:
      type: postgres
      threads: 4
      host: localhost
      port: 5433
      user: avito
      pass: avito123
      dbname: raw_dwh
      schema: core
  target: dev